### ISSUE TITLE
Syntax error.

### ISSUE THREAD

**Issue by LuckyRoc** [kishikawakatsumi/swift-ast-explorer-playground#2]
when i run your playground, will show "Syntax error."

"errno": -2,
"syscall": "open",
"code": "ENOENT",

**Comment by kishikawakatsumi** [comment]
@ChengRuipeng Please provide more info. What is your code?

**Comment by LuckyRoc** [comment]
I just clone your code and run "npm install" (not update your code)

![error](https://user-images.githubusercontent.com/10631829/54657198-6f8ce300-4b03-11e9-8136-7564e4ca741c.png)

**Comment by kishikawakatsumi** [comment]
OK, this repository is a frontend of https://github.com/kishikawakatsumi/swift-ast-explorer . 
You need to set up correctly the backend application first. It needs linux and tested only Ubuntu 16.04. You also set up linux environment or Docker.

If you just see Swift AST, you can use https://swift-ast-explorer.kishikawakatsumi.com/

@ChengRuipeng

**Comment by LuckyRoc** [comment]
Thank you very much! Where is your backend application ? I just want to know how  conversion Swift to AST

**Comment by kishikawakatsumi** [comment]
https://github.com/kishikawakatsumi/swift-ast-explorer

and it uses Apple's SwiftSyntax https://github.com/apple/swift-syntax

**Comment by LuckyRoc** [comment]
Ok! Thanks you very very very very much !
